core/urls.py
from django.urls import path
from .views import index,novoPedido,editaPedido,todosPedidos,muda_preco,delete_item,delete_pedido

app_name = 'core'
urlpatterns = [
    path('',index,name='index'),
    path('pedido',novoPedido,name='formularioPedido'),
    path('edita/<int:id>/<int:id2>/',editaPedido,name='editaPedido'),
    path('deleta/<int:id>/',delete_item,name='deleteItem'),
    path('deletap/<int:id>/',delete_pedido,name='deletePedido'),
    path('produtos',todosPedidos,name='todosPedidos'),
    path('ajax/muda-preco/',muda_preco, name='ajax_muda_preco'),
]

mercos/urls.py
from django.contrib import admin
from django.urls import path,include


urlpatterns = [
    path('',include('core.urls')),
    path('admin/', admin.site.urls),
    path('select2/', include('django_select2.urls')),
]

core/models.py
from django.db import models
from django.forms import NumberInput

class Pedido(models.Model):
    id = models.AutoField(primary_key=True)
    cliente = models.CharField(max_length=100)

class Item(models.Model):
    quantidade_digitada_pelo_usuario = models.IntegerField(default=1)
    preco_digitado_pelo_usuario = models.FloatField(default = 550000.00)
    produto = models.CharField(max_length=100)
    rentabilidade = models.CharField(max_length=100,null=True)
    referencia_pedido = models.ForeignKey(Pedido,on_delete=models.CASCADE)

core/forms.py
from django import forms
from django.forms import ModelForm,Select,NumberInput
from .models import Pedido,Item
from django.forms import Select
from decimal import Decimal
#Primeiro valor é o valor que sera usado o segundo da tupla e o que sera visto pelo usuario
#Clientes Pré Cadastrados
CLIENT_CHOICES = (('Darth​ ​Vader','Darth​ ​Vader'),
                     ('Obi-Wan​ ​Kenobi','Obi-Wan​ ​Kenobi'),
                     ('Luke​ ​Skywalker','Luke​ ​Skywalker'),
                     ('Imperador​ ​Palpatine','Imperador​ ​Palpatine'),
                     ('Han​ ​Solo','Han​ ​Solo'))
#Produtos Pré Cadastrados
PRODUCT_CHOICES = (('Millenium​ ​Falcon','Millenium​ ​Falcon'),
                     ('X-Wing','X-Wing'),
                     ('Super​ ​Star​ ​Destroyer','Super​ ​Star​ ​Destroyer'),
                     ('TIE​ ​Fighter','TIE​ ​Fighter'),
                     ('Lightsaber','Lightsaber'),
                     ('DLT-19​ ​Heavy​ ​Blaster​ ​Rifle','DLT-19​ ​Heavy​ ​Blaster​ ​Rifle'),
                     ('DL-44​ ​Heavy​ ​Blaster​ ​Pistol','DL-44​ ​Heavy​ ​Blaster​ ​Pistol'))

PRECO_PRODUTOS = {
    'Millenium​ ​Falcon':550000,
    'X-Wing':60000,
    'Super​ ​Star​ ​Destroyer':4570000,
    'TIE​ ​Fighter':75000,
    'Lightsaber':6000,
    'DLT-19​ ​Heavy​ ​Blaster​ ​Rifle':5800,
    'DL-44​ ​Heavy​ ​Blaster​ ​Pistol':1500
    }

MULTIPLO_PRODUTOS = {
    'Millenium​ ​Falcon':0,
    'X-Wing':2,
    'Super​ ​Star​ ​Destroyer':0,
    'TIE​ ​Fighter':2,
    'Lightsaber':5,
    'DLT-19​ ​Heavy​ ​Blaster​ ​Rifle':0,
    'DL-44​ ​Heavy​ ​Blaster​ ​Pistol':10
    }                      

class PedidoForm(forms.ModelForm):
    class Meta:
        model = Pedido
        fields = ['cliente']
        widgets = {'cliente': Select(choices=CLIENT_CHOICES)}


class ItemForm(forms.ModelForm):
    class Meta:
        model = Item
        fields = ['produto','quantidade_digitada_pelo_usuario','preco_digitado_pelo_usuario']   
        widgets = {'produto': Select(choices=PRODUCT_CHOICES),
                    'preco_digitado_pelo_usuario':NumberInput(attrs={'step':"0.01"})
                    } 
        labels = {'quantidade_digitada_pelo_usuario':'Quantidade','preco_digitado_pelo_usuario':'Preço'}

    #valida campos do formulario ao clicar no botão de adicionar ou salvar
    def clean_quantidade_digitada_pelo_usuario(self):
        quantity = self.cleaned_data['quantidade_digitada_pelo_usuario']
        product = self.cleaned_data['produto']
        multiplo = MULTIPLO_PRODUTOS[product]
        if(quantity <= 0):
            raise forms.ValidationError("Quantidade deve ser maior do que zero")
            #self.add_error('quantidade_digitada_pelo_usuario', msg)
        if(MULTIPLO_PRODUTOS[product] != 0):
            if((quantity % multiplo) != 0 ):
                raise forms.ValidationError("Nao atende as regras de multiplo")
        return quantity
    def clean_preco_digitado_pelo_usuario(self):
        price = self.cleaned_data['preco_digitado_pelo_usuario']
        product = self.cleaned_data['produto']
        if(price < (PRECO_PRODUTOS[product] - (PRECO_PRODUTOS[product]*0.1) )):         
                raise forms.ValidationError("Impossivel adicionar o item, somente itens com rentabilidade boa ou ótima podem ser adicionados")
        return price


    """def clean(self):
        cleaned_data = super().clean()
        #recupera os dados do formulario
        quantity = cleaned_data.get("quantidade_digitada_pelo_usuario")
        product = cleaned_data.get("produto")
        price = cleaned_data.get("preco_digitado_pelo_usuario")
        multiplo = MULTIPLO_PRODUTOS[product]
        error1 = False
        error2 = False
        error3 = False
        #verifica se o produto atende as regras de multiplo
        if(MULTIPLO_PRODUTOS[product] != 0):
            if((quantity % multiplo) != 0 ):
                error1 = True
                
        #verifica a rentabilidade se for ruim avisa ao usuário
        if(price < (PRECO_PRODUTOS[product] - (PRECO_PRODUTOS[product]*0.1) )):      
            error2=True
            
        #avisa que a quantidade do produto não pode ser igual ou menor do que zero
        if(quantity <= 0):
            error3=True

        #depedendo de quais campos não foram validados corretamente mostra mensagens de erro
        if(error1 and error2 and error3):
            raise forms.ValidationError([
                forms.ValidationError(('|Este produto precisa ser multiplo de %s|' % multiplo), code='error1'),
                forms.ValidationError(('|Rentabilidade Ruim|'), code='error2'),
                forms.ValidationError(('|Quantidade precisa ser maior do que zero|'), code='error3'),
            ])        
        if(error1 and error2):        
           raise forms.ValidationError([
                forms.ValidationError(('|Este produto precisa ser multiplo de %s|' % multiplo), code='error1'),
                forms.ValidationError(('|Rentabilidade Ruim|'), code='error2'),
            ])     
        if(error1 and error3):        
            raise forms.ValidationError([
                forms.ValidationError(('|Este produto precisa ser multiplo de %s|' % multiplo), code='error1'),
                forms.ValidationError(('|Quantidade precisa ser maior do que zero|'), code='error3'),
            ])     
        if (error2 and error3):
            raise forms.ValidationError([
                forms.ValidationError(('|Rentabilidade Ruim|'), code='error2'),
                forms.ValidationError(('|Quantidade precisa ser maior do que zero|'), code='error3'),
            ])     
        if(error1):  
            raise forms.ValidationError("Quantidade não é multipla de %s" % multiplo)
        if (error2):
            raise forms.ValidationError("Rentabilidade Ruim")            
        if (error3):
            raise forms.ValidationError("Quantidade precisa ser maior do que zero")    """
        
       

core/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect,HttpResponse
from django.urls import reverse
from .forms import ItemForm,PedidoForm
from .models import Item,Pedido
from django.shortcuts import get_object_or_404,redirect
#constantes
from .constantes import endi



#################Constantes#################3
PRECO_PRODUTOS = {
    'Millenium​ ​Falcon':550000,
    'X-Wing':60000,
    'Super​ ​Star​ ​Destroyer':4570000,
    'TIE​ ​Fighter':75000,
    'Lightsaber':6000,
    'DLT-19​ ​Heavy​ ​Blaster​ ​Rifle':5800,
    'DL-44​ ​Heavy​ ​Blaster​ ​Pistol':1500
    }

MULTIPLO_PRODUTOS = {
    'Millenium​ ​Falcon':0,
    'X-Wing':2,
    'Super​ ​Star​ ​Destroyer':0,
    'TIE​ ​Fighter':2,
    'Lightsaber':5,
    'DLT-19​ ​Heavy​ ​Blaster​ ​Rifle':0,
    'DL-44​ ​Heavy​ ​Blaster​ ​Pistol':10
    }   
################# Views abaixo ################
def muda_preco(request):
    produto = request.GET.get('produto')
    preco = PRECO_PRODUTOS[produto]
    #return HttpResponse(preco)
    return render(request, 'core/preco.html', {'preco': preco})
#renderiza a página inicial
def index(request):
    return render(request,'core/index.html')

def todosPedidos(request):
    p = Pedido.objects.all()
    i = Item.objects.all()
    return render(request,'core/pedidos.html',{'p':p,'i':i})

def delete_item(request,id):
    item = Item.objects.get(pk=id).delete()    
    p = Pedido.objects.all()
    i = Item.objects.all()
    return render(request,'core/pedidos.html',{'p':p,'i':i})

def delete_pedido(request,id):
    pedido = Pedido.objects.get(pk=id).delete()
    p = Pedido.objects.all()
    i = Item.objects.all()
    return render(request,'core/pedidos.html',{'p':p,'i':i})     

#trata o novo pedido
def novoPedido(request):
    adicionados=[]
    #se a requisição chega com o verbo POST processa os dados recebidos e realiza as operações necessárias
    if request.method == 'POST':
        form1 = PedidoForm(request.POST)
        form2 = ItemForm(request.POST)
        if (form1.is_valid() & form2.is_valid()):
            #processa os dados do formulario  e redireciona para alguma url
            client = form1.cleaned_data['cliente']
            product = form2.cleaned_data['produto']
            quantity = form2.cleaned_data['quantidade_digitada_pelo_usuario']
            price = form2.cleaned_data['preco_digitado_pelo_usuario']     
            lista_acumulada = request.session.get('lista_acumulada')
            # se o usuário clicar no botão salvar, salva os dados no banco
            if('Salvar' in request.POST):
                #adiciona item na lista e salva no banco de dados
                lista=[product,quantity,price]
                lista_acumulada.append(lista)
                context = {'lista_acumulada':lista_acumulada,'client':client,'tamanho':len(lista_acumulada)}
                p = Pedido.objects.create(cliente=client)
                p.save()
                i=0
                listaDeItens=[]
                while (i < len(lista_acumulada)):
                    rent = 'ruim'
                    #Verifica a rentabilidade do item adicionado
                    if(lista_acumulada[i][2] > PRECO_PRODUTOS[lista_acumulada[i][0]]):
                        rent =  'otima'
                    elif (lista_acumulada[i][2]  < (PRECO_PRODUTOS[lista_acumulada[i][0]] - (0.1*PRECO_PRODUTOS[lista_acumulada[i][0]]))):
                        rent = 'ruim'
                    else:
                        rent = 'boa'    
                 
                    item = Item(quantidade_digitada_pelo_usuario=lista_acumulada[i][1],
                    preco_digitado_pelo_usuario=lista_acumulada[i][2],
                    produto=lista_acumulada[i][0],
                    rentabilidade=rent,
                    referencia_pedido=p)
                    item.save()
                    i = i + 1
                    listaDeItens.append(item)
                 
                context = {'lista_acumulada':lista_acumulada,'client':client,'tamanho':len(lista_acumulada),'p':p,'item':listaDeItens}    
                #return render(request,'core/resultado.html',context)
                return redirect('core:todosPedidos')
                
            #se o usuário clicar no botão para adicionar um novo item    
            if('Adicionar' in request.POST):
                form2=ItemForm()

                #adiciona item a lista e salva na sessão
                lista=[product,quantity,price]
                lista_acumulada.append(lista)
                adicionados=lista_acumulada
                request.session['lista_acumulada'] = lista_acumulada
                return render(request,'core/novoPedido.html',{'form1':form1,'form2':form2,'adicionados':adicionados})
    else:
        #caso a requisição não chegue como POST renderiza o formulario no formato padrão para o usuário
        #se cancelar volta pra página inicial
        if('Cancelar' in request.GET):
            return HttpResponseRedirect(reverse('core:index'))
        #instancia os formulários vazios para que o usuário possa preencher
        form1 = PedidoForm()
        form2 = ItemForm()
        lista_acumulada=[]
        request.session['lista_acumulada'] =lista_acumulada
    adicionados=request.session['lista_acumulada'] #pega os itens já adicionados para informar ao usuário
    return render(request,'core/novoPedido.html',{'form1':form1,'form2':form2,'adicionados':adicionados})
  

def editaPedido(request, id, id2): 
    #caso o usuário clique em cancelar redireciona para a página que lista todos pedidos
    if('Cancelar' in request.POST):
            return HttpResponseRedirect(reverse('core:todosPedidos'))
    #caso contrário o resto do código é executado        
    instance = get_object_or_404(Pedido, id=id)
    formPedido = PedidoForm(request.POST or None, instance=instance)
    instance2 = get_object_or_404(Item, id=id2)
    formItem = ItemForm(request.POST or None, instance=instance2)
    if formPedido.is_valid() and formItem.is_valid():
        formPedido.save()
        formItem.save()
        return redirect('core:todosPedidos')
    return render(request, 'core/editaPedido.html', {'formPedido': formPedido,'formItem':formItem,'item':instance2})     

core/templates/core/base.html
{% load static %}
{% load staticfiles %}

<html>

    <head>
        <script src="{% static 'core/jquery-3.3.1.min.js' %}"></script>
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">        
        <link rel="stylesheet" type="text/css" href="{% static 'core/styles.css' %}" />
        <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"
      rel="stylesheet"
      integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN"
      crossorigin="anonymous"
>
        {% block head %}
        {% endblock %}
        <title>
            {% block title %}
            {% endblock %}
        </title>
    </head>
    <body >
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark" >
            <a class="navbar-brand" href="{% url 'core:index' %} " >Home</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
                <div class="navbar-nav" >
                    <a class="navbar-brand" href="{% url 'core:formularioPedido' %}">
                       Novo Pedido
                    </a>                    
                    <a class="navbar-brand" href="{% url 'core:todosPedidos'%}">
                       Todos Pedidos
                    </a>
                </div>
            </div>
        </nav>   
        
        <div class="container word-wrap" >
                <br>   
           <div class="row">
                <div role="main" class="col-md-9" >
                    {% block main %}
            
                    {%  endblock %}
                </div>
                <aside role="complementary" class="col-md-3" >
                    <h3 align="center"> Pedidos  </h3>
                    <ul class="list-group">
                        
                        <li class="list-group-item"><a href="{% url 'core:formularioPedido' %}" class="btn btn-primary"> Criar um novo pedido </a></li>
                        <li class="list-group-item"><a href="{% url 'core:todosPedidos' %}" class="btn btn-primary">Visualizar todos os pedidos</a></li>
                         
                    </ul>
                    <br>
         
                        
                    {% block aside %}
                        
                    {%  endblock %}
                </aside>
            </div>
            <footer class="row">
                
            </footer>       
        </div>
        
        
       
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    </body>

</html>

core/templates/core/editaPedido.html
{% extends 'core/base.html' %}
{% load bootstrap %}
{% load static %}
{% block main %}

    <h3 align="center">Editar Pedido</h3> 

    <form action="" method="POST" id="pedidoForm" muda_preco_url="{% url 'core:ajax_muda_preco' %}">
        {% csrf_token %}
        {{formPedido|bootstrap}}
        {{formItem.produto|bootstrap}}
        {{formItem.quantidade_digitada_pelo_usuario|bootstrap}}
        <div id="quantidade" style="color:rgb(109, 109, 3); margin-bottom: 5px" ></div>
        {{formItem.preco_digitado_pelo_usuario|bootstrap}}
        <div id="rentabilidade" style="color:green" >
            Rentabilidade {{item.rentabilidade}}
        </div>
        <input type="submit" value="Salvar" name="Salvar" class="btn btn-success">
        <input type="submit" value="Cancelar" name="Cancelar" class="btn btn-danger">
    </form>

    <script type="module" src="{% static 'core/rentabilidade.js' %}"></script>
    <script type="module" src="{% static 'core/validacao.js' %}"></script>
{% endblock %}

core/templates/core/index.html
{% extends 'core/base.html' %}

{% block main %}   
                <h1 class="display-4" align="center">Seja bem vindo</h1>
                <p class="lead">Este é um site dedicado a realização de pedidos utilizando as tabelas de clientes e produtos que podem ser conferidas abaixo.</p>
                <hr class="my-4">

                <h3 align="center">Produtos</h3>
                <table class="table">
                        <thead class="thead-dark">
                            <tr>
                            <th class="tg-s268">ID</th>
                            <th class="tg-s268">Nome</th>
                            <th class="tg-s268">Preço (R$)</th>
                            <th class="tg-s268">Múltiplo</th>
                            </tr>
                        </thead>
                        <tr>
                          <td class="tg-s268">1</td>
                          <td class="tg-s268">Millenium Falcon</td>
                          <td class="tg-s268">550.000,00</td>
                          <td class="tg-s268"></td>
                        </tr>
                        <tr>
                          <td class="tg-s268">2</td>
                          <td class="tg-s268">X-Wing</td>
                          <td class="tg-s268">60.000,00</td>
                          <td class="tg-s268">2</td>
                        </tr>
                        <tr>
                          <td class="tg-s268">3</td>
                          <td class="tg-s268">Super Star Destroyer</td>
                          <td class="tg-s268">4.570.000,00</td>
                          <td class="tg-s268"></td>
                        </tr>
                        <tr>
                          <td class="tg-s268">4</td>
                          <td class="tg-s268">TIE Fighter</td>
                          <td class="tg-s268">75.000,00</td>
                          <td class="tg-s268">2</td>
                        </tr>
                        <tr>
                          <td class="tg-s268">5</td>
                          <td class="tg-s268">Lightsaber</td>
                          <td class="tg-s268">6.000,00</td>
                          <td class="tg-s268">5</td>
                        </tr>
                        <tr>
                          <td class="tg-s268">6</td>
                          <td class="tg-s268">DLT-19 Heavy Blaster Rifle</td>
                          <td class="tg-s268">5.800,00</td>
                          <td class="tg-s268"></td>
                        </tr>
                        <tr>
                          <td class="tg-s268">7</td>
                          <td class="tg-s268">DL-44 Heavy Blaster Pistol</td>
                          <td class="tg-s268">1.500,00</td>
                          <td class="tg-s268">10</td>
                        </tr>
                </table>    
                      
                      <hr class="my-4">
                      <h3 align="center">Clientes</h3>
                              <table class="table">
                                <thead class="thead-dark">
                                    <tr>
                                    <th class="tg-s268">ID</th>
                                    <th class="tg-s268">Nome</th>
                                    </tr>
                                </thead>
                                <tr>
                                  <td class="tg-s268">1</td>
                                  <td class="tg-s268">Darth​ ​Vader</td>
                                </tr>
                                <tr>
                                  <td class="tg-s268">2</td>
                                  <td class="tg-s268">Obi-Wan​ ​Kenobi</td>
                                </tr>
                                <tr>
                                  <td class="tg-s268">3</td>
                                  <td class="tg-s268">Luke​ ​Skywalker</td>
                                </tr>
                                <tr>
                                  <td class="tg-s268">4</td>
                                  <td class="tg-s268">Imperador​ ​Palpatine</td>
                                </tr>
                                <tr>
                                  <td class="tg-s268">5</td>
                                  <td class="tg-s268">Han​ ​Solo</td>
                                </tr>
                              </table>
{%endblock %}

core/templates/core/novoPedido.html
{% extends 'core/base.html' %}
{% load bootstrap %}
{% load static %}
{% block main %}



    <h3 align="center">Novo Pedido</h3>
        
    <form action="" method="post" id="pedidoForm" muda_preco_url="{% url 'core:ajax_muda_preco' %}">
        {% csrf_token %}
        {{ form1|bootstrap }}

        {{ form2.produto|bootstrap  }}

        {{ form2.quantidade_digitada_pelo_usuario|bootstrap }} 

        <div id="quantidade" style="color:rgb(109, 109, 3); margin-bottom: 5px" ></div>
        
        {{ form2.preco_digitado_pelo_usuario|bootstrap }} 
        <div id="rentabilidade" style="color:green; margin-bottom: 5px" > </div>
        
        <input type="submit" value="Adicionar novo Item" name="Adicionar" class="btn btn-primary" >
        <input type="submit" value="Salvar Pedido" name="Salvar" class="btn btn-success">
    </form>
        
    <form>
        <input type="submit" value="Cancelar" name="Cancelar" class="btn btn-danger">
    </form>

    <script type="module" src="{% static 'core/rentabilidade.js' %}"></script>
    <script type="module" src="{% static 'core/validacao.js' %}"></script>
    <hr class="my-4">

    {% if adicionados %}
        <h3>Resumo do pedido</h3>
       
        <table class="table">
                <thead class="thead-dark">
                  <tr>
                    <th scope="col">Produto</th>
                    <th scope="col">Quantidade</th>
                    <th scope="col">Preço</th>
                  </tr>
                </thead>
                <tbody>
                        {% for i in adicionados %}
                        <tr>
                            <td>{{i.0}}</td>
                            <td>{{i.1}}</td>
                            <td>{{i.2}}</td>
                        </tr>
                        {% endfor %}
                </tbody>
        </table>
        
    {% endif %}




{% endblock %}

core/templates/core/pedidos.html
{% extends 'core/base.html' %}
{% load icons %}
{% block main %}
    <h1 align="center">Todos os Pedidos</h1>
    {% for pedido in p  %}
    <h3 align="center">Pedido {{pedido.id }}  <a href="{% url 'core:deletePedido' pedido.id %}" class="btn btn-danger"> Deletar Pedido </a></h3>
    <table class="table">
        <thead class="thead-dark">
          <tr>
           
            <th scope="col">Cliente</th>
            <th scope="col">Produto</th>
            <th scope="col">Quantidade</th>
            <th scope="col">Preço</th>
            <th scope="col">Rentabilidade</th>
            <th scope="col"> </th>
          </tr>
        </thead>
        <tbody>
        {% for item in i %}
            {% if item.referencia_pedido == pedido %}
                <tr>
                    
                    <td> {{pedido.cliente}}</td>
                    <td>{{item.produto}}</td>
                    <td align="center">{{item.quantidade_digitada_pelo_usuario}}</td>
                    <td>{{item.preco_digitado_pelo_usuario}}</td>
                    <td align="center">{{item.rentabilidade}}</td>
                    <td><a href="{% url 'core:editaPedido' pedido.id item.id%}" class="btn btn-warning"> {% icon 'pencil' %} </a>
                        <a href="{% url 'core:deleteItem' item.id %}" class="btn btn-danger"> {% icon 'trash' %} </a></td>
                </tr>
          {% endif %} 
        {%endfor%}  
        </tbody>
      </table>
      <hr class="my-4">

      {%endfor%}


{% endblock %} 

core/templates/core/pedidos2.html
{% extends 'core/base.html' %}
{% block main %}
    <h1 align="center">Todos os Pedidos</h1>
        
    {% for pedido in p  %}
    <br>  <br>    
    <h3>Pedido {{pedido.id }}</h3>
    <ul class="list-group" ></ul>      
        <li class="list-group-item">Cliente: {{pedido.cliente}}</li>
        {% for item in i %}
            {% if item.referencia_pedido == pedido %}
                <li class="list-group-item">Produto: {{item.produto}}</li>
                <li class="list-group-item">Quantidade: {{item.quantidade_digitada_pelo_usuario}}</li>
                <li class="list-group-item">Preço: {{item.preco_digitado_pelo_usuario}}</li>
                <li class="list-group-item">Rentabilidade: {{item.rentabilidade}}</li>
                <li class="list-group-item" ><a href="{% url 'core:editaPedido' pedido.id item.id %}" class="btn btn-warning"> Editar Item </a>
                <a href="{% url 'core:deleteItem' item.id %}" class="btn btn-danger"> Deletar Item </a>  </li> 
            {% endif %}    
        {%endfor%}
        <li class="list-group-item" ><a href="{% url 'core:deletePedido' pedido.id %}" class="btn btn-danger"> Deletar Pedido </a></li> 
    {%endfor%}
    </ul>
{% endblock %} 

core/templates/core/preco.html
{{preco}}